import '../css/bootstrap.min.css'
import '../css/sb-admin-2.min.css'
import '../css/styles.css'
import '../untitled folder/assets/js/jquery-3.6.0.js'
import '../untitled folder/assets/js/bootstrap.min.js'
import '../untitled folder/assets/js/sb-admin-2.min.js'
